// <auto-generated />
namespace ShopBazr.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initiate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initiate));
        
        string IMigrationMetadata.Id
        {
            get { return "202008200730255_initiate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
